import { StrictMode } from 'react'
import { createRoot } from 'react-dom/client'
import { createRouter, RouterProvider } from '@tanstack/react-router'
import { QueryClient, QueryClientProvider } from '@tanstack/react-query'
import { ReactQueryDevtools } from '@tanstack/react-query-devtools'

// This file is auto-generated by TanStack Router — don't edit it manually
import { routeTree } from './routeTree.gen'

import './index.css'

/**
 * The router is TanStack Router's brain.
 * It reads the routeTree (auto-generated from your files in routes/)
 * and knows which component to render for each URL.
 */
const router = createRouter({ routeTree })

/**
 * TypeScript needs to know about our router for full type safety.
 * This tells TypeScript: "when I use useNavigate() or Link, 
 * the valid routes are exactly what's in our routeTree."
 */
declare module '@tanstack/react-router' {
  interface Register {
    router: typeof router
  }
}

/**
 * QueryClient is TanStack Query's brain.
 * It manages all your server state — caching, background refetching, etc.
 * staleTime: how long before data is considered old and needs refetching.
 * retry: how many times to retry a failed request.
 */
const queryClient = new QueryClient({
  defaultOptions: {
    queries: {
      staleTime: 1000 * 60 * 5, // 5 minutes
      retry: 1,
    },
  },
})

createRoot(document.getElementById('root')!).render(
  <StrictMode>
    {/*
      QueryClientProvider makes the queryClient available to every
      component in the tree. Like a global store for server data.
    */}
    <QueryClientProvider client={queryClient}>
      <RouterProvider router={router} />
      <ReactQueryDevtools initialIsOpen={false} />
    </QueryClientProvider>
  </StrictMode>,
)